version: '3.8' 

services:
  app:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
      - ./core/store.sqlite3:/app/core/store.sqlite3
    ports:
      - "7755:7755"
    environment:
      GUNICORN_PORT: 7755
      GUNICORN_NUMBER_WORKERS: 2
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./core/store.sqlite3:/data/store.sqlite3
    restart: unless-stopped

networks:
  default:
    driver: bridge
